
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: preim
  password: preim

development:
  <<: *default
  database: BudgetTrackr_development

test:
  <<: *default
  database: BudgetTrackr_test

production:
  <<: *default
  database: BudgetTrackr_production